version: '3'

services:
# Dynamic DNS service to auto-update Cloudflare records on public IP change
# See: https://hub.docker.com/r/oznu/cloudflare-ddns/
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: host
    restart: always
    environment:
      # Add API_KEY to .env file in this directory;
      # File needs to be created and is gitignored.
      - ZONE=cywang.top
      - PROXIED=true
      - RRTYPE=A
      - DNS_SERVER=1.1.1.1
    env_file: .env
