version: '3'

services:
# Secure Web Application Gateway
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - URL=cywang.top
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./swag-reverse-proxy:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - swag
    restart: unless-stopped

networks:
  swag:
    external: true